// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"@@/global-layout","id":"1"},"2":{"path":"/home","title":"首页","parentId":"@@/global-layout","id":"2"},"3":{"path":"/todo","title":"待做","parentId":"@@/global-layout","id":"3"},"4":{"path":"/message","title":"消息","parentId":"@@/global-layout","id":"4"},"5":{"path":"/account","title":"我的","parentId":"@@/global-layout","id":"5"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__home" */'@/pages/home.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__todo" */'@/pages/todo.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__message" */'@/pages/message.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__account" */'@/pages/account.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/joenix/Github/@vue-scaff-template/src/layouts/index.tsx')),
},
  };
}
